package com.astrohark.app.utils

object Localization {
    // English Strings
    private val english = mapOf(
        "home_title" to "astrohark",
        "home" to "Home",
        "profile" to "Profile",
        "settings" to "Settings",
        "logout" to "Logout",
        "join_as_astrologer" to "Join as Astrologer",
        "name" to "Full Name",
        "phone_number" to "Phone Number",
        "email_address" to "Email Address",
        "experience_years" to "Experience (Years)",
        "skills_expert" to "Skills (e.g. Vedic, Tarot)",
        "price_per_min" to "Price Per Min",
        "about_you" to "About You",
        "register_now" to "Register Now",
        "premium_consultation" to "Premium Consultation",
        "vedic_remedies" to "Vedic Remedies",
        "gemstone_guide" to "Gemstone Guide",
        "horoscope" to "Horoscope",
        "daily_horoscope" to "Daily Horoscope",
        "chat_services" to "Chat Services",
        "video_call" to "Video Call",
        "audio_call" to "Audio Call",
        "view_all" to "View All",
        "loading" to "Loading...",
        "aries" to "Aries",
        "taurus" to "Taurus",
        "gemini" to "Gemini",
        "cancer" to "Cancer",
        "leo" to "Leo",
        "virgo" to "Virgo",
        "libra" to "Libra",
        "scorpio" to "Scorpio",
        "sagittarius" to "Sagittarius",
        "capricorn" to "Capricorn",
        "aquarius" to "Aquarius",
        "pisces" to "Pisces",
        "all" to "All",
        "love" to "Love",
        "career" to "Career",
        "finance" to "Finance",
        "marriage" to "Marriage",
        "health" to "Health",
        "education" to "Education",
        "element" to "Element",
        "lord" to "Lord",
        "category" to "Category",
        "daily_prediction" to "Daily Prediction",
        "ok" to "OK",
        "personal_details" to "Personal Details",
        "partner_details" to "Partner Details",
        "dob" to "Date of Birth",
        "tob" to "Time of Birth",
        "pob" to "Place of Birth",
        "gender" to "Gender",
        "male" to "Male",
        "female" to "Female",
        "occupation" to "Occupation",
        "marital_status" to "Marital Status",
        "topic" to "Problem Topic",
        "submit_consultation" to "Start Consultation",
        "unknown_time" to "I don't know my birth time",
        "select_city" to "Select City",
        "full_name" to "Full Name",
        "single" to "Single",
        "married" to "Married",
        "divorced" to "Divorced",
        "widowed" to "Widowed",
        "career_/_job" to "Career / Job",
        "marriage_/_relationship" to "Marriage / Relationship",
        "health" to "Health",
        "finance" to "Finance",
        "legal" to "Legal",
        "general" to "General",
        "basic_info" to "Basic Information",
        "birth_details" to "Birth Details",
        "contact_details" to "Contact Information",
        "professional_details" to "Professional Details",
        "payment_details" to "Payment Details",
        "real_name" to "Real Name (as per Aadhar)",
        "display_name" to "Display Name",
        "whatsapp_number" to "WhatsApp Number",
        "full_address" to "Full Address",
        "aadhar_number" to "Aadhar Number",
        "pan_number" to "PAN Number",
        "bank_details" to "Bank Details (A/C, IFSC)",
        "upi_id" to "UPI ID / Name",
        "please_fill_required" to "Please fill required fields (*)"
    )

    // Tamil Strings
    private val tamil = mapOf(
        "home_title" to "ஆஸ்ட்ரோ 5 ஸ்டார்",
        "home" to "முகப்பு",
        "profile" to "சுயவிவரம்",
        "settings" to "அமைப்புகள்",
        "logout" to "வெளியேறு",
        "join_as_astrologer" to "ஜோதிடராக இணையுங்கள்",
        "name" to "முழு பெயர்",
        "phone_number" to "தொலைபேசி எண்",
        "email_address" to "மின்னஞ்சல் முகவரி",
        "experience_years" to "அனுபவம் (ஆண்டுகள்)",
        "skills_expert" to "திறன்கள் (உதாரணம்: வேத, டாரோட்)",
        "price_per_min" to "நிமிடத்திற்கு கட்டணம்",
        "about_you" to "உங்களைப் பற்றி",
        "register_now" to "பதிவு செய்க",
        "premium_consultation" to "பிரீமியம் ஆலோசனை",
        "vedic_remedies" to "வேத பரிகாரங்கள்",
        "gemstone_guide" to "ரத்தின வழிகாட்டி",
        "horoscope" to "ராசி பலன்",
        "daily_horoscope" to "தினசரி ராசி பலன்",
        "chat_services" to "சாட் சேவை",
        "video_call" to "வீடியோ அழைப்பு",
        "audio_call" to "ஆடியோ அழைப்பு",
        "view_all" to "அனைத்தையும் பார்க்க",
        "loading" to "ஏற்றுகிறது...",
        "aries" to "மேஷம்",
        "taurus" to "ரிஷபம்",
        "gemini" to "மிதுனம்",
        "cancer" to "கடகம்",
        "leo" to "சிம்மம்",
        "virgo" to "கன்னி",
        "libra" to "துலாம்",
        "scorpio" to "விருச்சிகம்",
        "sagittarius" to "தனுசு",
        "capricorn" to "மகரம்",
        "aquarius" to "கும்பம்",
        "pisces" to "மீனம்",
        "all" to "அனைத்தும்",
        "love" to "காதல்",
        "career" to "வேலைவாய்ப்பு",
        "finance" to "நிதி",
        "marriage" to "திருமணம்",
        "health" to "உடல்நலம்",
        "education" to "கல்வி",
        "element" to "தத்துவம்",
        "lord" to "அதிபதி",
        "category" to "வகை",
        "daily_prediction" to "இன்றைய பலன்",
        "ok" to "சரி",
        "personal_details" to "தனிப்பட்ட விவரங்கள்",
        "partner_details" to "துணைவர் விவரங்கள்",
        "dob" to "பிறந்த தேதி",
        "tob" to "பிறந்த நேரம்",
        "pob" to "பிறந்த இடம்",
        "gender" to "பாலினம்",
        "male" to "ஆண்",
        "female" to "பெண்",
        "occupation" to "தொழில்",
        "marital_status" to "திருமண நிலை",
        "topic" to "கேள்வித் தலைப்பு",
        "submit_consultation" to "ஆலோசனையைத் தொடங்கவும்",
        "unknown_time" to "பிறந்த நேரம் தெரியவில்லை",
        "select_city" to "நகரத்தைத் தேர்ந்தெடுக்கவும்",
        "full_name" to "முழு பெயர்",
        "single" to "திருமணமாகாதவர்",
        "married" to "திருமணமானவர்",
        "divorced" to "விவாகரத்தானவர்",
        "widowed" to "துணையை இழந்தவர்",
        "career_/_job" to "வேலை / தொழில்",
        "marriage_/_relationship" to "திருமணம் / உறவு",
        "health" to "உடல்நலம்",
        "finance" to "நிதி",
        "legal" to "சட்டம்",
        "general" to "பொதுவானது",
        "basic_info" to "அடிப்படை விவரங்கள்",
        "birth_details" to "பிறப்பு விவரங்கள்",
        "contact_details" to "தொடர்பு விவரங்கள்",
        "professional_details" to "தொழில்முறை விவரங்கள்",
        "payment_details" to "கட்டண விவரங்கள்",
        "real_name" to "உண்மையான பெயர் (ஆதார் படி)",
        "display_name" to "காட்சி பெயர்",
        "whatsapp_number" to "வாட்ஸ்அப் எண்",
        "full_address" to "முழு முகவரி",
        "aadhar_number" to "ஆதார் எண்",
        "pan_number" to "பான் எண்",
        "bank_details" to "வங்கி விவரங்கள் (A/C, IFSC)",
        "upi_id" to "UPI விவரம்",
        "please_fill_required" to "சிவப்பு நட்சத்திரம் (*) உள்ள கட்டாய புலங்களை நிரப்பவும்"
    )

    fun get(key: String, isTamil: Boolean): String {
        return if (isTamil) {
            tamil[key] ?: english[key] ?: key
        } else {
            english[key] ?: key
        }
    }
}
